[package]
name = "models"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
serde_with = "3.4.0"

uuid = { version = "1.6.1", features = ["v4", "serde"] }
