use serde::{Deserialize, Serialize};
/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.2
 *
 * Generated by: https://openapi-generator.tech
 */

/// EasIpReplacementInfo : Contains EAS IP replacement information for a Source and a Target EAS.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EasIpReplacementInfo {
    #[serde(rename = "source")]
    pub source: Box<crate::EasServerAddress>,
    #[serde(rename = "target")]
    pub target: Box<crate::EasServerAddress>,
}

impl EasIpReplacementInfo {
    /// Contains EAS IP replacement information for a Source and a Target EAS.
    pub fn new(
        source: crate::EasServerAddress,
        target: crate::EasServerAddress,
    ) -> EasIpReplacementInfo {
        EasIpReplacementInfo {
            source: Box::new(source),
            target: Box::new(target),
        }
    }
}
